FROM openjdk:8-jre-slim

ARG talend_job=testsimple
ARG talend_version=0_1

LABEL maintainer="mgainhao@talend.com" \
    talend.job=${talend_job} \
    talend.version=${talend_version}

ENV TALEND_JOB ${talend_job}
ENV TALEND_VERSION ${talend_version}
ENV ARGS ""


WORKDIR /opt/talend


COPY job_sample_job_cicd_test_in_jenkins_0_2.zip .
RUN pwd
### Install Talend Job
RUN apt-get update -y && \
    apt-get install -y unzip && \
    unzip job_sample_job_cicd_test_in_jenkins_0_2.zip && \
    rm -rf job_sample_job_cicd_test_in_jenkins_0_2.zip && \
    chmod +x TestSimple/TestSimple_run.sh

VOLUME /data

CMD ["/bin/sh","-c","job_sample_job_CICD_test_In_Jenkins/job_sample_job_CICD_test_In_Jenkins_run.sh"]
